### ISSUE TITLE
A tool to find js files just by giving the domain name. 

### ISSUE THREAD

**Issue by streaak** [bugbountyforum/ideas#1]
# Summary

# What problem are you trying to solve?
Automate the task of feeding js files to linkfinder and/or having all js files in one place. 

# Example situation where this tool could be helpful
For testing for XSSI, feeding js files to linkfinder and loads more 

# Is this tool already under development?
I don't think so 

- [ ] This tool is currently under development. **Link:**
- [ ✓] This tool is *not* currently under development.

# Are there any similar tools already out there?

- [ ] Yes. **Link:**
- [ ✓] No.

---

# Checklist

- [✓ ] I have verified that there are no similar tickets already open.
- [✓ ] I am willing to contribute to the development of this tool.
- [ ✓] I am willing to pay someone a small fee to create this tool.

**Comment by t3h2mas** [comment]
What sort of limits would the spidering functionality for this have?

**Comment by 003random** [comment]
i got 2 similar tools for that; https://github.com/003random/003Recon/blob/master/tools/javascript_files_extractor.py and https://github.com/003random/003Recon/blob/master/tools/javascript_files_link_extractor.sh You can check in the recon.sh file how to call them with parameters

**Comment by EdOverflow** [comment]
**🚨 A tool was found that fullfills the requirements listed above.** 

Thank you for submitting this ticket.

---

**Tool:** https://github.com/bugbountyforum/ideas/issues/1#issuecomment-349014771

**Comment by karelorigin** [comment]
```
import requests, json, sys

if len(sys.argv) != 3:
	print "Usage: \"python main.py http(s)://<domain>/ <file-name>.txt\""
	raise SystemExit

def endpoints(host):
	global returned_endpoints
	r = requests.get("http://web.archive.org/cdx/search?url=%s&matchType=prefix&collapse=urlkey&output=json&fl=original,mimetype,timestamp,endtimestamp,groupcount,uniqcount&filter=statuscode:[200]..&limit=100000000&_=1508419249886" % host);
	returned_endpoints = r.json()
	returned_endpoints.pop(0)

def checkstatus(url):
	s = requests.Session()
	s.keep_alive = False
	headers = {"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"}
	print(url)
	try:
		status = s.get(url, headers=headers, timeout=10).status_code
		obj["host"]["status"][str(status)].append(url)
	except (KeyError, requests.exceptions.TooManyRedirects, requests.exceptions.ReadTimeout, requests.exceptions.ConnectionError) as e:
		pass

endpoints(sys.argv[1])

obj = {"host":{"status":{"200":[], "404":[], "403":[]}}}

for x in returned_endpoints:
	if "javascript" in x[1]:
		checkstatus(x[0]);

file = open("output/%s" % sys.argv[2], 'w')
file.write(json.dumps(obj))
file.close()
```

What about this?
